---
name: Build
on: [push]
jobs:
  python-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 api/
  run-tests:
    needs: python-formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Start Flask app
        run: |
          cd api
          export supabase_url=${{ secrets.SUPABASE_URL }}
          export supabase_key=${{ secrets.SUPABASE_KEY }}
          nohup python app.py &

      - name: Wait for app to start
        run: sleep 10

      - name: Run tests
        run: |
          cd api
          export supabase_url=${{ secrets.SUPABASE_URL }}
          export supabase_key=${{ secrets.SUPABASE_KEY }}
          python app_test.py
